name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i -g yarn
        yarn install
        yarn test
      env:
        CI: true
        REACT_APP_PUBLIC_KEY: ${{ secrets.ik_public_key }}
        REACT_APP_PRIVATE_KEY: ${{ secrets.ik_private_key }}
        REACT_APP_URL_ENDPOINT: ${{ secrets.ik_url_endopint }}
